README
src/vfd/sriov.c

The changes in commit b6c43e06b6c527368271a04e680780d25a438149 placed
the dpdk_1604 changes back in. Grrrr.
This reverts the sriov.c back to 2.2 code, and removes the note in the
main readme that indicates it's 1604 only.

Revert sriov.c back to dpdk 2.2.

---

src/vfd/vfd_rif.c

Correcting VFID range check to VFID < 0

vfid range check

---

src/vfd/Makefile
src/vfd/sriov.c
src/vfd/sriov.h
src/vfd/vfd_dcb.c

Requires DPDK build from https://github.com/Broadcom/dpdk.git on the
16.11_base branch to build with BNXT support.
make BNXT_SUPPORT=yes
Will build with bnxt support.

Initial VFd support for Broadcom bnxt devices

---

doc/master.mk
src/lib/Makefile
src/lib/config.c
src/lib/jw_xapi.c
src/lib/jwrapper.c
src/lib/mkfile
src/lib/parm_file_test.c
src/lib/parm_file_test.cfg
src/lib/vfdlib.h
src/vfd/main.c
src/vfd/qos.c
src/vfd/sriov.c
src/vfd/sriov.h

The setting of the drop enable bit was changed to prevent the NIC from losing packets. 
The setting of the hardware strip crc value now defaults to true and may be configured in the main parm file for each PF.

Drop enable and HW crc strip default changes

---

src/vfd/sriov.c

vf_stats_display is using port_pci_reg_read() which is using ixgbe
specific offsets. Use rte_pmd_bnxt_get_vf_stats instead for bnxt.
Signed-off-by: Ajit Khaparde <ajit.khaparde@broadcom.com>

use rte_pmd_bnxt_get_vf_stats to get stats for bnxt devices

---

src/vfd/main.c
src/vfd/sriov.c
src/vfd/sriov.h

Two commits:
1) ensure that the jumbo frame flag in the dev default description is set to true
2) ensure that the enable loopback (tx switching) is reset on the NIC after renegotiate callback if it is configured for the port in our config file.  We saw evidence that the NIC was dropping this setting for at least one of the ports when the physical link went down and came back up (with a direct attached host on the other side of the wire rather than a switch).

Ensure jumbo set, ensure loopback set

---

src/lib/config.c
src/package/vfd_debian/copyright
src/vfd/main.c
src/vfd/vfd_rif.c

Three commits:
- fix copyright in the package directory that implied 'internal use only'; not removed when a skeleton directory was used to seed the package directory.
- allow multiple VLAN IDs to be supplied when stripping is set to true
- Set the max allowable MTU from the config to 9.2K; slightly larger than what seems standard jumbo-gram size.

Cap MTU, fix copyright, support multiple VLANs with strip

---

src/vfd/main.c
src/vfd/sriov.c
src/vfd/sriov.h

Read the capabilities for all the ports and save the VF_offfset/stride appropriately to correctly enumerate VFs for non-zero ports.

enumerate SRIOV caps for all the ports

---

src/vfd/main.c
src/vfd/sriov.c
src/vfd/sriov.h

expand spoffed to 64-bits
clean up multi-nic support so same binary can suport BNXT and Intel
include TX errors and drops in VF output with bnxt
enforce MAC addresses listed in config file
- If there's no MACs listed, the MAC anti-spoof is somewhat disabled
- This is done using the callback and denying HWRM calls that change
or add MAC addresses

Tx mac fixes

---

src/lib/fifo.c
src/lib/vfdlib.h
src/system/Makefile
src/system/mkfile
src/system/vreq.c

Adding vreq tool to the system library. Vreq is a C based request interface which supports only the general user requests (ping, show, dump) to VFd.   This C based implementation can be installed as a root suid binary allowing normal uses the ability to show NIC stats for VFd managed PF/VF combinations without having to have sudo/root credentials.    Vreq assumes the VFd fifo (pipe.channel) is in the default location, but an alternate location can be supplied on the command line using the -c option.  This allows for easier testing when needed.   Vreq does _not_ read the VFd config file. 
An additional function was added to the fifo module in the library to support this.

Add vreq tool

---

src/vfd/sriov.c

Allowing VFs to change MAC is a side-effect of Intel requirement to
enable MAC anti-spoof whenever VLAN anti-spoof is enabled.  Since
Broadcom doesn't have this limiation, the expectation is that MAC
anti-spoof will be disabled and VLAN anti-spoof will be enabled.

Per AT&T call, enable MAC address change enforcment.

---

src/vfd/sriov.c

Check if the MAC address specified in VF config file is valid.
This will prevent the is_valid_ether_addr() or is_multicast_ether_addr()
in native Linux network stack from complaining.

check if the MAC address in VF config is valid

---

src/lib/config.c
src/lib/vfdlib.h
src/vfd/main.c
src/vfd/sriov.c
src/vfd/sriov.h

The initial setting of flow control was specific to Niantic NICs. These changes use the dpdk library to set flow control, and allow it to be set from the config file or the command line.

Make flow control dpdk based

---

src/lib/config.c
src/vfd/main.c
src/vfd/sriov.c
src/vfd/sriov.h
src/vfd/vfd_bnxt.c
src/vfd/vfd_bnxt.h
src/vfd/vfd_ixgbe.c
src/vfd/vfd_ixgbe.h
src/vfd/vfd_rif.c

Add MAC setting to accomodate FV single function and use both BC functions
Add changes to support single mac as string in VF config
Force MAC antispoofing only for niantic; forced off for other NICs now

Nic agnostic

---

src/vfd/sriov.c

Works around issue where strip would be left on.  A proper driver fix
will be put into the 17.08 DPDK branch.

Reconfigure VF stripq after turning off insert.

---

src/vfd/sriov.c

Also, disable promiscuous when broadcast is disabled.

Ensure the multicast table is cleared when multicast is not allowed

---

src/vfd/main.c
src/vfd/sriov.c
src/vfd/vfd_rif.c

Bug fixes which were causing invalid error counts to show for Niantic nic in show all output.
Reorganised the port init code, and fixed bugs there (main.c):
-- code to set offset/stride was outside of the block that prevented updates to ports that
are not in the VFd config (and thus should be untouched)
-- code to get information to set offset/stride was commented out for both boradcom and niantic
-- code to get information from Mellanox NIC was unguarded
-- invalid indexes were being used to reference the port struct in the running config 
If add_ports was called more than once it would leave the spin lock in a locked state. (vfd_rif.c)

Nic agnostic - bug fixes

---

doc/hackers/vfd_hackers.xfm
src/vfd/Makefile
src/vfd/main.c

Based on DPDK 18.02 release notes:
During rte_eal_init() EAL allocates memory from hugepages to enable its core libraries to perform their tasks. The rte_eal_cleanup() function releases these resources, ensuring that no hugepage memory is leaked. It is expected that all DPDK applications call rte_eal_cleanup() before exiting. Not calling this function could result in leaking hugepages, leading to failure during initialization of secondary processes.

added rte_eal_cleanup during VFd termination

---

src/vfd/main.c
src/vfd/vfd_mac.c
src/vfd/vfd_rif.c

There were a couple of places where the index into the mac table for a VF wasn't computed correctly. We use a 1 based offset unless the guest 'registers' a default which is placed into slot 0; makes getting the right start/stop index right a bit less straight forward (as evidenced by the bugs).

Mac list indexing fixes + cleanup

---

src/vfd/vfd_rif.c

Double free removed from add vf function.   VFd now removes bad configs from the live directory when errors detected on start.

Correct bug (i296) double free in vfd_rif

---

src/system/vfd.conf

VFD must be started and initialized BEFORE nova-compute.
`iplex ping` is used in order to prevent nova-compute
from starting too early when VFD is still initializing its state.
Also, unused `start on` is deleted.

Block VFD daemon on post-start stage

---

src/support/tests/requirements.txt

The security problem github keeps nattering on about is caused if we require paramiko < 2.2.4. This is just a test tool, so no real issue, but fixed anyway.

Update paramiko requirement to advance past versions with security isues

---

src/lib/Makefile
src/lib/jw_xapi.c
src/lib/jwrapper.c
src/lib/jwrapper_test.ksh
src/lib/mkfile
src/lib/test_all.ksh
src/vfd/Makefile

Jsmn no longer generates a library. These changes are needed to properly build the vfd library with jsmn code.

Adjust for jsmn changes

---

src/vfd/sriov.h
src/vfd/vfd_dcb.h

The if defs broke as soon as the year moved to 19.

Correct bad ifdef referencing DPDK versions >= 19.02
